apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongodb-spc
  namespace: klikgo
spec:
  provider: azure
  secretObjects:
    - secretName: mongodb-secrets
      type: Opaque
      data:
        - objectName: MONGO-INITDB-ROOT-USERNAME
          key: MONGO_INITDB_ROOT_USERNAME
        - objectName: MONGO-INITDB-ROOT-PASSWORD
          key: MONGO_INITDB_ROOT_PASSWORD
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "672a633d-7014-405b-85c6-fec088550d37"
    keyvaultName: "klikgo-kv"
    tenantId: "6e76b77a-5ff3-4afd-b8d2-087d8e14ac09"
    objects: |
      array:
        - |
          objectName: MONGO-INITDB-ROOT-USERNAME
          objectType: secret
        - |
          objectName: MONGO-INITDB-ROOT-PASSWORD
          objectType: secret