apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: klikgo
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:satish123@mongodb:27017/?authSource=admin"
  JWT_SECRET_KEY: "Satish7"
  PRODUCT_SERVICE_URL: "http://product-service:8001/api/v1"
  PAYMENT_SERVICE_URL: "http://payment-service:8003/api/v1"