apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-service-spc
  namespace: klikgo
spec:
  provider: azure
  secretObjects:
    - secretName: auth-service-secrets
      type: Opaque
      data:
        - objectName: MONGO-URI
          key: MONGO_URI
        - objectName: JWT-SECRET-KEY
          key: JWT_SECRET_KEY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "672a633d-7014-405b-85c6-fec088550d37"
    keyvaultName: "klikgo-kv"
    tenantId: "6e76b77a-5ff3-4afd-b8d2-087d8e14ac09"
    objects: |
      array:
        - |
          objectName: MONGO-URI
          objectType: secret
        - |
          objectName: JWT-SECRET-KEY
          objectType: secret