apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
  namespace: klikgo
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:satish123@mongodb:27017/?authSource=admin"
  JWT_SECRET_KEY: "Satish7"
  ORDER_SERVICE_URL: "http://order-service:8002/api/v1"