apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: ecommerce
data:
  APP_NAME: "product Service"
  APP_VERSION: "1.0.0"
  API_PREFIX: "/api/v1"

  HOST: "0.0.0.0"
  PORT: "8001"

  DATABASE_NAME: "ecommerce_db"

  JWT_ALGORITHM: "HS256"
  JWT_ISSUER: "auth-service"
