apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: klikgo
  labels:
    app: product-service
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: klikgoacr.azurecr.io/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001

          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3